export const gridData = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    department: "Marketing",
    position: "Marketing Manager",
    status: "Active",
    lastLogin: "2023-06-15T09:30:00",
    joinDate: "2020-03-12",
    salary: 85000,
    projects: 5,
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    department: "Sales",
    position: "Sales Representative",
    status: "Active",
    lastLogin: "2023-06-18T14:15:00",
    joinDate: "2019-07-22",
    salary: 72000,
    projects: 8,
  },
  {
    id: 3,
    name: "Robert Johnson",
    email: "robert.j@example.com",
    department: "IT",
    position: "Senior Developer",
    status: "Inactive",
    lastLogin: "2023-04-20T11:20:00",
    joinDate: "2018-05-10",
    salary: 95000,
    projects: 12,
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily.d@example.com",
    department: "HR",
    position: "HR Manager",
    status: "Active",
    lastLogin: "2023-06-10T16:45:00",
    joinDate: "2021-01-15",
    salary: 78000,
    projects: 3,
  },
  {
    id: 5,
    name: "Michael Wilson",
    email: "michael.w@example.com",
    department: "Finance",
    position: "Financial Analyst",
    status: "Active",
    lastLogin: "2023-06-17T10:10:00",
    joinDate: "2020-09-05",
    salary: 82000,
    projects: 7,
  },
  {
    id: 6,
    name: "Sarah Brown",
    email: "sarah.b@example.com",
    department: "Marketing",
    position: "Content Specialist",
    status: "Inactive",
    lastLogin: "2023-03-22T13:25:00",
    joinDate: "2019-11-18",
    salary: 68000,
    projects: 4,
  },
  {
    id: 7,
    name: "David Taylor",
    email: "david.t@example.com",
    department: "IT",
    position: "DevOps Engineer",
    status: "Active",
    lastLogin: "2023-06-19T08:50:00",
    joinDate: "2022-02-28",
    salary: 105000,
    projects: 9,
  },
  {
    id: 8,
    name: "Jessica Martinez",
    email: "jessica.m@example.com",
    department: "Sales",
    position: "Account Executive",
    status: "Active",
    lastLogin: "2023-06-14T15:30:00",
    joinDate: "2021-06-10",
    salary: 88000,
    projects: 11,
  },
  {
    id: 9,
    name: "Thomas Anderson",
    email: "thomas.a@example.com",
    department: "Finance",
    position: "CFO",
    status: "Inactive",
    lastLogin: "2023-02-28T17:20:00",
    joinDate: "2017-08-15",
    salary: 150000,
    projects: 15,
  },
  {
    id: 10,
    name: "Lisa Jackson",
    email: "lisa.j@example.com",
    department: "HR",
    position: "Recruiter",
    status: "Active",
    lastLogin: "2023-06-16T12:40:00",
    joinDate: "2022-04-05",
    salary: 65000,
    projects: 6,
  },
];

export const statuses = [
  { text: "Active", value: "Active" },
  { text: "Inactive", value: "Inactive" },
  { text: "Pending", value: "Pending" },
];

export const departments = [
  { text: "Marketing", value: "Marketing" },
  { text: "Sales", value: "Sales" },
  { text: "IT", value: "IT" },
  { text: "HR", value: "HR" },
  { text: "Finance", value: "Finance" },
];
